#!/bin/bash
#
# deployment.sh - Deployment helper functions for Rushomon
#
# This library provides:
#   - Frontend and backend build
#   - Wrangler configuration generation
#   - Database migration application
#   - Worker deployment
#   - Deployment validation
#

# Source common utilities if not already loaded
if [ -z "$BLUE" ]; then
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  source "$SCRIPT_DIR/common.sh"
  source "$SCRIPT_DIR/cloudflare.sh"
  source "$SCRIPT_DIR/validation.sh"
fi

# Generate wrangler.toml configuration
generate_wrangler_config() {
  local output_file="$1"
  local env="${2:-production}"

  info "Generating wrangler configuration: $output_file"

  # Ensure required variables are set
  if [ -z "$WORKER_NAME" ] || [ -z "$D1_DATABASE_ID" ] || [ -z "$KV_NAMESPACE_ID" ]; then
    error "Missing required configuration variables"
    return 1
  fi

  cat > "$output_file" <<EOF
# Generated by setup.sh on $(date)
# Environment: ${env}

name = "${WORKER_NAME}"
main = "build/worker/shim.mjs"
compatibility_date = "2026-02-10"
upload_source_maps = true

# Account ID for Cloudflare
account_id = "${CLOUDFLARE_ACCOUNT_ID}"

[observability]
enabled = true
head_sampling_rate = 1

[observability.traces]
enabled = true
head_sampling_rate = 0.1

[[d1_databases]]
binding = "rushomon"
database_id = "${D1_DATABASE_ID}"

[[kv_namespaces]]
binding = "URL_MAPPINGS"
id = "${KV_NAMESPACE_ID}"

[assets]
directory = "./frontend/build"
binding = "ASSETS"
run_worker_first = true
not_found_handling = "none"

[vars]
GITHUB_CLIENT_ID = "${GITHUB_CLIENT_ID}"
GITHUB_AUTHORIZE_URL = "https://github.com/login/oauth/authorize"
GITHUB_TOKEN_URL = "https://github.com/login/oauth/access_token"
GITHUB_USER_URL = "https://api.github.com/user"
EOF

  # Add Google OAuth if enabled
  if [ "$GOOGLE_ENABLED" = true ] && [ -n "$GOOGLE_CLIENT_ID" ]; then
    cat >> "$output_file" <<EOF
GOOGLE_CLIENT_ID = "${GOOGLE_CLIENT_ID}"
GOOGLE_AUTHORIZE_URL = "https://accounts.google.com/o/oauth2/v2/auth"
GOOGLE_TOKEN_URL = "https://oauth2.googleapis.com/token"
GOOGLE_USER_URL = "https://openidconnect.googleapis.com/v1/userinfo"
EOF
  fi

  # Add domain configuration
  cat >> "$output_file" <<EOF
DOMAIN = "${API_DOMAIN}"
FRONTEND_URL = "https://${MAIN_DOMAIN}"
ALLOWED_ORIGINS = "https://${MAIN_DOMAIN},https://${API_DOMAIN}"
ENABLE_KV_RATE_LIMITING = "${ENABLE_KV_RATE_LIMITING:-false}"
EOF

  # Add Mailgun configuration if enabled
  if [ -n "$MAILGUN_DOMAIN" ]; then
    cat >> "$output_file" <<EOF
MAILGUN_DOMAIN = "${MAILGUN_DOMAIN}"
MAILGUN_BASE_URL = "${MAILGUN_BASE_URL}"
MAILGUN_FROM = "${MAILGUN_FROM}"
EOF
  fi

  # Add custom domain routes
  info "Adding custom domain routes for ${DOMAIN_STRATEGY:-single} domain strategy..."

  if [ "${DOMAIN_STRATEGY:-single}" = "single" ]; then
    # Single domain strategy - only add one route
    cat >> "$output_file" <<EOF

# Custom domains - single domain strategy
[[routes]]
pattern = "${MAIN_DOMAIN}"
custom_domain = true
EOF
  else
    # Multi-domain strategy - add routes for all domains
    cat >> "$output_file" <<EOF

# Custom domains - multi-domain strategy
[[routes]]
pattern = "${MAIN_DOMAIN}"
custom_domain = true

[[routes]]
pattern = "${API_DOMAIN}"
custom_domain = true

[[routes]]
pattern = "${REDIRECT_DOMAIN}"
custom_domain = true
EOF
  fi

  success "Wrangler configuration generated: $output_file"
  return 0
}

# Check build prerequisites
check_build_prerequisites() {
  info "Checking build prerequisites..."

  # Check Node.js
  if ! command -v node &>/dev/null; then
    error "Node.js not found"
    info "Install from: https://nodejs.org/"
    return 1
  fi

  local node_version=$(node --version)
  info "Node.js version: $node_version"

  # Check npm
  if ! command -v npm &>/dev/null; then
    error "npm not found"
    return 1
  fi

  # Check Rust
  if ! command -v cargo &>/dev/null; then
    error "Rust not found"
    info "Install from: https://rustup.rs/"
    return 1
  fi

  local rust_version=$(cargo --version)
  info "Rust version: $rust_version"

  # Check worker-build
  if ! command -v worker-build &>/dev/null; then
    warning "worker-build not found, installing..."
    cargo install worker-build || {
      error "Failed to install worker-build"
      return 1
    }
  fi

  local worker_build_version=$(worker-build --version 2>/dev/null || echo "unknown")
  info "worker-build version: $worker_build_version"

  success "Build prerequisites check passed"
  return 0
}

# Build backend (Rust Worker)
build_backend() {
  local project_root="${1:-.}"

  info "Building backend..."

  cd "$project_root" || return 1

  # Run worker-build in release mode
  worker-build --release || {
    error "Backend build failed"
    return 1
  }

  success "Backend built successfully"
  return 0
}

# Install frontend dependencies
install_frontend_dependencies() {
  local project_root="${1:-.}"

  info "Installing frontend dependencies..."

  cd "$project_root/frontend" || {
    error "Frontend directory not found"
    return 1
  }

  npm ci || {
    error "Failed to install frontend dependencies"
    return 1
  }

  success "Frontend dependencies installed"
  return 0
}

# Build frontend
build_frontend() {
  local project_root="${1:-.}"

  info "Building frontend..."

  cd "$project_root/frontend" || return 1

  # Set environment variables for frontend build
  export PUBLIC_VITE_API_BASE_URL="https://${API_DOMAIN}"
  export PUBLIC_VITE_SHORT_LINK_BASE_URL="https://${REDIRECT_DOMAIN}"

  info "  API URL: $PUBLIC_VITE_API_BASE_URL"
  info "  Redirect URL: $PUBLIC_VITE_SHORT_LINK_BASE_URL"

  # Build frontend
  npm run build || {
    error "Frontend build failed"
    return 1
  }

  success "Frontend built successfully"
  return 0
}

# Apply database migrations
apply_migrations() {
  local config_file="${1:-wrangler.toml}"
  local project_root="${2:-.}"

  info "Applying database migrations..."

  cd "$project_root" || return 1

  # Extract database name from config
  local db_name=$(grep -A 2 '\[\[d1_databases\]\]' "$config_file" | grep 'binding' | head -1 | cut -d'"' -f2)

  if [ -z "$db_name" ]; then
    error "Could not find database binding in $config_file"
    return 1
  fi

  # Apply migrations
  wrangler d1 migrations apply "$db_name" --remote --config "$config_file" || {
    error "Failed to apply migrations"
    return 1
  }

  success "Database migrations applied"
  return 0
}

# Set Worker secrets
set_worker_secrets() {
  local config_file="${1:-wrangler.toml}"

  info "Setting Worker secrets..."

  # Set GitHub client secret
  if [ -n "$GITHUB_CLIENT_SECRET" ]; then
    echo "$GITHUB_CLIENT_SECRET" | wrangler secret put GITHUB_CLIENT_SECRET --config "$config_file" || {
      error "Failed to set GITHUB_CLIENT_SECRET"
      return 1
    }
    success "  - GITHUB_CLIENT_SECRET set"
  fi

  # Set Google client secret (if enabled)
  if [ "$GOOGLE_ENABLED" = true ] && [ -n "$GOOGLE_CLIENT_SECRET" ]; then
    echo "$GOOGLE_CLIENT_SECRET" | wrangler secret put GOOGLE_CLIENT_SECRET --config "$config_file" || {
      error "Failed to set GOOGLE_CLIENT_SECRET"
      return 1
    }
    success "  - GOOGLE_CLIENT_SECRET set"
  fi

  # Set JWT secret
  if [ -n "$JWT_SECRET" ]; then
    echo "$JWT_SECRET" | wrangler secret put JWT_SECRET --config "$config_file" || {
      error "Failed to set JWT_SECRET"
      return 1
    }
    success "  - JWT_SECRET set"
  else
    error "JWT_SECRET not set"
    return 1
  fi

  # Set Mailgun API key (if configured)
  if [ -n "$MAILGUN_API_KEY" ]; then
    echo "$MAILGUN_API_KEY" | wrangler secret put MAILGUN_API_KEY --config "$config_file" || {
      error "Failed to set MAILGUN_API_KEY"
      return 1
    }
    success "  - MAILGUN_API_KEY set"
  fi

  success "Worker secrets configured"
  return 0
}

# Deploy Worker
deploy_worker_to_cloudflare() {
  local config_file="${1:-wrangler.toml}"
  local project_root="${2:-.}"

  info "Deploying Worker to Cloudflare..."

  cd "$project_root" || return 1

  wrangler deploy --config "$config_file" || {
    error "Worker deployment failed"
    return 1
  }

  success "Worker deployed successfully"
  return 0
}

# Full deployment orchestration
deploy_environment() {
  local config_file="${1:-wrangler.toml}"
  local project_root="${2:-.}"

  info "Starting deployment process..."

  # Check prerequisites
  if ! check_build_prerequisites; then
    return 1
  fi

  # Create Cloudflare resources
  info "Creating Cloudflare resources..."

  export D1_DATABASE_ID=$(create_or_get_d1_database "$WORKER_NAME" || echo "")
  if [ -z "$D1_DATABASE_ID" ]; then
    error "Failed to create/get D1 database"
    return 1
  fi

  export KV_NAMESPACE_ID=$(create_or_get_kv_namespace "URL_MAPPINGS_${ENVIRONMENT_NAME}" || echo "")
  if [ -z "$KV_NAMESPACE_ID" ]; then
    error "Failed to create/get KV namespace"
    return 1
  fi

  # Generate wrangler config
  if ! generate_wrangler_config "$config_file" "$ENVIRONMENT_NAME"; then
    return 1
  fi

  # Build backend
  if ! build_backend "$project_root"; then
    return 1
  fi

  # Install and build frontend
  if ! install_frontend_dependencies "$project_root"; then
    return 1
  fi

  if ! build_frontend "$project_root"; then
    return 1
  fi

  # Apply database migrations
  if ! apply_migrations "$config_file" "$project_root"; then
    return 1
  fi

  # Set Worker secrets
  if ! set_worker_secrets "$config_file"; then
    return 1
  fi

  # Deploy Worker
  if ! deploy_worker_to_cloudflare "$config_file" "$project_root"; then
    return 1
  fi

  success "Deployment completed successfully"
  return 0
}

# Show deployment summary
show_deployment_summary() {
  echo ""
  echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo -e "${GREEN}Deployment Summary${NC}"
  echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo ""
  echo -e "${GREEN}Environment:${NC} ${ENVIRONMENT_NAME}"
  echo -e "${GREEN}Worker Name:${NC} ${WORKER_NAME}"
  echo ""
  echo -e "${GREEN}Domains:${NC}"
  echo "  - Main (Web):     https://${MAIN_DOMAIN}"
  echo "  - API:            https://${API_DOMAIN}"
  echo "  - Redirects:      https://${REDIRECT_DOMAIN}"
  echo ""
  echo -e "${GREEN}Cloudflare Resources:${NC}"
  echo "  - D1 Database:    ${D1_DATABASE_ID}"
  echo "  - KV Namespace:   ${KV_NAMESPACE_ID}"
  echo ""
  echo -e "${GREEN}OAuth & Email Providers:${NC}"

  if [ "$GITHUB_ENABLED" = true ]; then
    echo "  - GitHub OAuth:   Enabled"
  else
    echo "  - GitHub OAuth:   Disabled"
  fi

  if [ "$GOOGLE_ENABLED" = true ]; then
    echo "  - Google OAuth:   Enabled"
  else
    echo "  - Google OAuth:   Disabled"
  fi

  if [ -n "$MAILGUN_DOMAIN" ]; then
    echo "  - Mailgun:        Enabled (team invitations)"
  else
    echo "  - Mailgun:        Disabled"
  fi

  echo ""
  echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo ""
  echo -e "${GREEN}Next Steps:${NC}"
  echo ""
  echo "1. Test your deployment:"
  echo -e "   ${CYAN}https://${MAIN_DOMAIN}${NC}"
  echo ""
  echo "2. Configure your instance at:"
  echo -e "   ${CYAN}https://${MAIN_DOMAIN}/admin/settings${NC}"
  echo "   - Disable user signup"
  echo "   - Upgrade your user to the unlimited plan"
  echo ""
  echo "3. Create your first short link by logging in"
  echo ""
  echo -e "${YELLOW}Important:${NC} Keep your configuration file and secrets secure."
  echo "            Never commit secrets to version control."
  echo ""
  echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo ""
}

# Rollback deployment
rollback_deployment() {
  local config_file="$1"
  local backup_file="$2"

  warning "Rolling back deployment..."

  if [ -z "$backup_file" ] || [ ! -f "$backup_file" ]; then
    error "No backup file available for rollback"
    return 1
  fi

  # Restore database from backup
  if [ -f "$SCRIPT_DIR/../restore.sh" ]; then
    "$SCRIPT_DIR/../restore.sh" -f -c "$config_file" "$backup_file" || {
      error "Failed to restore database"
      return 1
    }
  else
    warning "Restore script not found, cannot rollback database"
  fi

  success "Rollback completed"
  return 0
}
